# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://aggarwalsarthak.github.io/
baseurl: /
title: Sarthak Aggarwal
author: Sarthak Aggarwal
description: Personal blog and resume
avatar: sarthak.png
email: sarthakaggarwal97@gmail.com
github: sarthakaggarwal97 # username
twitter: username
linkedin: sarthakaggarwal97
stackoverflow: username   #e.g: users/2735833/proton1h1
medium: username #e.g: NobelPeaceOslo
#Comment out if you don't want disqus
disqus: username
google_analytics: G-M0D09V41H0


# needed for travis-ci build
exclude: [vendor]
